// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add.proto

package com.example.tutorial;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string user_type = 1;
    boolean hasUserType();
    String getUserType();
    
    // required string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // required string name = 3;
    boolean hasName();
    String getName();
    
    // required string nameGuardian = 4;
    boolean hasNameGuardian();
    String getNameGuardian();
    
    // required string SocietyPlotNumber = 5;
    boolean hasSocietyPlotNumber();
    String getSocietyPlotNumber();
    
    // required string ShopNo = 6;
    boolean hasShopNo();
    String getShopNo();
    
    // required string address = 7;
    boolean hasAddress();
    String getAddress();
    
    // repeated string contactNumber = 8;
    java.util.List<String> getContactNumberList();
    int getContactNumberCount();
    String getContactNumber(int index);
    
    // required double plotArea = 9;
    boolean hasPlotArea();
    double getPlotArea();
    
    // required string Mouza = 10;
    boolean hasMouza();
    String getMouza();
    
    // required string emailID = 11;
    boolean hasEmailID();
    String getEmailID();
    
    // required int32 AD_LandRent = 12;
    boolean hasADLandRent();
    int getADLandRent();
    
    // required int32 WC_Charges = 13;
    boolean hasWCCharges();
    int getWCCharges();
    
    // required int32 AD_Conservancy = 14;
    boolean hasADConservancy();
    int getADConservancy();
    
    // required int32 LF_Fee = 15;
    boolean hasLFFee();
    int getLFFee();
    
    // required int32 AD_ElectricityCharges = 16;
    boolean hasADElectricityCharges();
    int getADElectricityCharges();
    
    // required int32 previousMeterReading = 17;
    boolean hasPreviousMeterReading();
    int getPreviousMeterReading();
    
    // required int64 ID = 18;
    boolean hasID();
    long getID();
    
    // required int32 LR_StreetLight = 19;
    boolean hasLRStreetLight();
    int getLRStreetLight();
    
    // required int32 LR_DevTax = 20;
    boolean hasLRDevTax();
    int getLRDevTax();
    
    // required int32 LR_ExDevTax = 21;
    boolean hasLRExDevTax();
    int getLRExDevTax();
    
    // required int32 LR_Rent = 22;
    boolean hasLRRent();
    int getLRRent();
    
    // required int32 LR_Interest = 23;
    boolean hasLRInterest();
    int getLRInterest();
    
    // required int32 LR_Rebate = 24;
    boolean hasLRRebate();
    int getLRRebate();
    
    // required int32 WC_Interest = 25;
    boolean hasWCInterest();
    int getWCInterest();
    
    // required int32 WC_DevTax = 26;
    boolean hasWCDevTax();
    int getWCDevTax();
    
    // required int32 EC_Interest = 27;
    boolean hasECInterest();
    int getECInterest();
    
    // required int32 EC_MeterRent = 28;
    boolean hasECMeterRent();
    int getECMeterRent();
    
    // required int32 EC_FuseCall = 29;
    boolean hasECFuseCall();
    int getECFuseCall();
    
    // required int32 EC_Rent = 30;
    boolean hasECRent();
    int getECRent();
    
    // required int32 LF_Rebate = 31;
    boolean hasLFRebate();
    int getLFRebate();
    
    // required int32 LF_Interest = 32;
    boolean hasLFInterest();
    int getLFInterest();
    
    // required int32 currentMeterReading = 33;
    boolean hasCurrentMeterReading();
    int getCurrentMeterReading();
    
    // required int32 monthlyLicenseFee = 34;
    boolean hasMonthlyLicenseFee();
    int getMonthlyLicenseFee();
  }
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(Builder builder) {
      super(builder);
    }
    private Person(boolean noInit) {}
    
    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }
    
    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.AddressBookProtos.internal_static_tutorial_Person_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.AddressBookProtos.internal_static_tutorial_Person_fieldAccessorTable;
    }
    
    private int bitField0_;
    private int bitField1_;
    // required string user_type = 1;
    public static final int USER_TYPE_FIELD_NUMBER = 1;
    private java.lang.Object userType_;
    public boolean hasUserType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserType() {
      java.lang.Object ref = userType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserTypeBytes() {
      java.lang.Object ref = userType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string nameGuardian = 4;
    public static final int NAMEGUARDIAN_FIELD_NUMBER = 4;
    private java.lang.Object nameGuardian_;
    public boolean hasNameGuardian() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getNameGuardian() {
      java.lang.Object ref = nameGuardian_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nameGuardian_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameGuardianBytes() {
      java.lang.Object ref = nameGuardian_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nameGuardian_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string SocietyPlotNumber = 5;
    public static final int SOCIETYPLOTNUMBER_FIELD_NUMBER = 5;
    private java.lang.Object societyPlotNumber_;
    public boolean hasSocietyPlotNumber() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getSocietyPlotNumber() {
      java.lang.Object ref = societyPlotNumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          societyPlotNumber_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSocietyPlotNumberBytes() {
      java.lang.Object ref = societyPlotNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        societyPlotNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string ShopNo = 6;
    public static final int SHOPNO_FIELD_NUMBER = 6;
    private java.lang.Object shopNo_;
    public boolean hasShopNo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getShopNo() {
      java.lang.Object ref = shopNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          shopNo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getShopNoBytes() {
      java.lang.Object ref = shopNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        shopNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string address = 7;
    public static final int ADDRESS_FIELD_NUMBER = 7;
    private java.lang.Object address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          address_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string contactNumber = 8;
    public static final int CONTACTNUMBER_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList contactNumber_;
    public java.util.List<String>
        getContactNumberList() {
      return contactNumber_;
    }
    public int getContactNumberCount() {
      return contactNumber_.size();
    }
    public String getContactNumber(int index) {
      return contactNumber_.get(index);
    }
    
    // required double plotArea = 9;
    public static final int PLOTAREA_FIELD_NUMBER = 9;
    private double plotArea_;
    public boolean hasPlotArea() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public double getPlotArea() {
      return plotArea_;
    }
    
    // required string Mouza = 10;
    public static final int MOUZA_FIELD_NUMBER = 10;
    private java.lang.Object mouza_;
    public boolean hasMouza() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getMouza() {
      java.lang.Object ref = mouza_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mouza_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMouzaBytes() {
      java.lang.Object ref = mouza_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mouza_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string emailID = 11;
    public static final int EMAILID_FIELD_NUMBER = 11;
    private java.lang.Object emailID_;
    public boolean hasEmailID() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getEmailID() {
      java.lang.Object ref = emailID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          emailID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailIDBytes() {
      java.lang.Object ref = emailID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        emailID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 AD_LandRent = 12;
    public static final int AD_LANDRENT_FIELD_NUMBER = 12;
    private int aDLandRent_;
    public boolean hasADLandRent() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getADLandRent() {
      return aDLandRent_;
    }
    
    // required int32 WC_Charges = 13;
    public static final int WC_CHARGES_FIELD_NUMBER = 13;
    private int wCCharges_;
    public boolean hasWCCharges() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public int getWCCharges() {
      return wCCharges_;
    }
    
    // required int32 AD_Conservancy = 14;
    public static final int AD_CONSERVANCY_FIELD_NUMBER = 14;
    private int aDConservancy_;
    public boolean hasADConservancy() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getADConservancy() {
      return aDConservancy_;
    }
    
    // required int32 LF_Fee = 15;
    public static final int LF_FEE_FIELD_NUMBER = 15;
    private int lFFee_;
    public boolean hasLFFee() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public int getLFFee() {
      return lFFee_;
    }
    
    // required int32 AD_ElectricityCharges = 16;
    public static final int AD_ELECTRICITYCHARGES_FIELD_NUMBER = 16;
    private int aDElectricityCharges_;
    public boolean hasADElectricityCharges() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public int getADElectricityCharges() {
      return aDElectricityCharges_;
    }
    
    // required int32 previousMeterReading = 17;
    public static final int PREVIOUSMETERREADING_FIELD_NUMBER = 17;
    private int previousMeterReading_;
    public boolean hasPreviousMeterReading() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public int getPreviousMeterReading() {
      return previousMeterReading_;
    }
    
    // required int64 ID = 18;
    public static final int ID_FIELD_NUMBER = 18;
    private long iD_;
    public boolean hasID() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public long getID() {
      return iD_;
    }
    
    // required int32 LR_StreetLight = 19;
    public static final int LR_STREETLIGHT_FIELD_NUMBER = 19;
    private int lRStreetLight_;
    public boolean hasLRStreetLight() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    public int getLRStreetLight() {
      return lRStreetLight_;
    }
    
    // required int32 LR_DevTax = 20;
    public static final int LR_DEVTAX_FIELD_NUMBER = 20;
    private int lRDevTax_;
    public boolean hasLRDevTax() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    public int getLRDevTax() {
      return lRDevTax_;
    }
    
    // required int32 LR_ExDevTax = 21;
    public static final int LR_EXDEVTAX_FIELD_NUMBER = 21;
    private int lRExDevTax_;
    public boolean hasLRExDevTax() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    public int getLRExDevTax() {
      return lRExDevTax_;
    }
    
    // required int32 LR_Rent = 22;
    public static final int LR_RENT_FIELD_NUMBER = 22;
    private int lRRent_;
    public boolean hasLRRent() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    public int getLRRent() {
      return lRRent_;
    }
    
    // required int32 LR_Interest = 23;
    public static final int LR_INTEREST_FIELD_NUMBER = 23;
    private int lRInterest_;
    public boolean hasLRInterest() {
      return ((bitField0_ & 0x00200000) == 0x00200000);
    }
    public int getLRInterest() {
      return lRInterest_;
    }
    
    // required int32 LR_Rebate = 24;
    public static final int LR_REBATE_FIELD_NUMBER = 24;
    private int lRRebate_;
    public boolean hasLRRebate() {
      return ((bitField0_ & 0x00400000) == 0x00400000);
    }
    public int getLRRebate() {
      return lRRebate_;
    }
    
    // required int32 WC_Interest = 25;
    public static final int WC_INTEREST_FIELD_NUMBER = 25;
    private int wCInterest_;
    public boolean hasWCInterest() {
      return ((bitField0_ & 0x00800000) == 0x00800000);
    }
    public int getWCInterest() {
      return wCInterest_;
    }
    
    // required int32 WC_DevTax = 26;
    public static final int WC_DEVTAX_FIELD_NUMBER = 26;
    private int wCDevTax_;
    public boolean hasWCDevTax() {
      return ((bitField0_ & 0x01000000) == 0x01000000);
    }
    public int getWCDevTax() {
      return wCDevTax_;
    }
    
    // required int32 EC_Interest = 27;
    public static final int EC_INTEREST_FIELD_NUMBER = 27;
    private int eCInterest_;
    public boolean hasECInterest() {
      return ((bitField0_ & 0x02000000) == 0x02000000);
    }
    public int getECInterest() {
      return eCInterest_;
    }
    
    // required int32 EC_MeterRent = 28;
    public static final int EC_METERRENT_FIELD_NUMBER = 28;
    private int eCMeterRent_;
    public boolean hasECMeterRent() {
      return ((bitField0_ & 0x04000000) == 0x04000000);
    }
    public int getECMeterRent() {
      return eCMeterRent_;
    }
    
    // required int32 EC_FuseCall = 29;
    public static final int EC_FUSECALL_FIELD_NUMBER = 29;
    private int eCFuseCall_;
    public boolean hasECFuseCall() {
      return ((bitField0_ & 0x08000000) == 0x08000000);
    }
    public int getECFuseCall() {
      return eCFuseCall_;
    }
    
    // required int32 EC_Rent = 30;
    public static final int EC_RENT_FIELD_NUMBER = 30;
    private int eCRent_;
    public boolean hasECRent() {
      return ((bitField0_ & 0x10000000) == 0x10000000);
    }
    public int getECRent() {
      return eCRent_;
    }
    
    // required int32 LF_Rebate = 31;
    public static final int LF_REBATE_FIELD_NUMBER = 31;
    private int lFRebate_;
    public boolean hasLFRebate() {
      return ((bitField0_ & 0x20000000) == 0x20000000);
    }
    public int getLFRebate() {
      return lFRebate_;
    }
    
    // required int32 LF_Interest = 32;
    public static final int LF_INTEREST_FIELD_NUMBER = 32;
    private int lFInterest_;
    public boolean hasLFInterest() {
      return ((bitField0_ & 0x40000000) == 0x40000000);
    }
    public int getLFInterest() {
      return lFInterest_;
    }
    
    // required int32 currentMeterReading = 33;
    public static final int CURRENTMETERREADING_FIELD_NUMBER = 33;
    private int currentMeterReading_;
    public boolean hasCurrentMeterReading() {
      return ((bitField0_ & 0x80000000) == 0x80000000);
    }
    public int getCurrentMeterReading() {
      return currentMeterReading_;
    }
    
    // required int32 monthlyLicenseFee = 34;
    public static final int MONTHLYLICENSEFEE_FIELD_NUMBER = 34;
    private int monthlyLicenseFee_;
    public boolean hasMonthlyLicenseFee() {
      return ((bitField1_ & 0x00000001) == 0x00000001);
    }
    public int getMonthlyLicenseFee() {
      return monthlyLicenseFee_;
    }
    
    private void initFields() {
      userType_ = "";
      title_ = "";
      name_ = "";
      nameGuardian_ = "";
      societyPlotNumber_ = "";
      shopNo_ = "";
      address_ = "";
      contactNumber_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      plotArea_ = 0D;
      mouza_ = "";
      emailID_ = "";
      aDLandRent_ = 0;
      wCCharges_ = 0;
      aDConservancy_ = 0;
      lFFee_ = 0;
      aDElectricityCharges_ = 0;
      previousMeterReading_ = 0;
      iD_ = 0L;
      lRStreetLight_ = 0;
      lRDevTax_ = 0;
      lRExDevTax_ = 0;
      lRRent_ = 0;
      lRInterest_ = 0;
      lRRebate_ = 0;
      wCInterest_ = 0;
      wCDevTax_ = 0;
      eCInterest_ = 0;
      eCMeterRent_ = 0;
      eCFuseCall_ = 0;
      eCRent_ = 0;
      lFRebate_ = 0;
      lFInterest_ = 0;
      currentMeterReading_ = 0;
      monthlyLicenseFee_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNameGuardian()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSocietyPlotNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasShopNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlotArea()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMouza()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmailID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasADLandRent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWCCharges()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasADConservancy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLFFee()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasADElectricityCharges()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPreviousMeterReading()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLRStreetLight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLRDevTax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLRExDevTax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLRRent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLRInterest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLRRebate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWCInterest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWCDevTax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasECInterest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasECMeterRent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasECFuseCall()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasECRent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLFRebate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLFInterest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrentMeterReading()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMonthlyLicenseFee()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameGuardianBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSocietyPlotNumberBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getShopNoBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getAddressBytes());
      }
      for (int i = 0; i < contactNumber_.size(); i++) {
        output.writeBytes(8, contactNumber_.getByteString(i));
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(9, plotArea_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(10, getMouzaBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, getEmailIDBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(12, aDLandRent_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(13, wCCharges_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(14, aDConservancy_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(15, lFFee_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(16, aDElectricityCharges_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(17, previousMeterReading_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt64(18, iD_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeInt32(19, lRStreetLight_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeInt32(20, lRDevTax_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeInt32(21, lRExDevTax_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeInt32(22, lRRent_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        output.writeInt32(23, lRInterest_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        output.writeInt32(24, lRRebate_);
      }
      if (((bitField0_ & 0x00800000) == 0x00800000)) {
        output.writeInt32(25, wCInterest_);
      }
      if (((bitField0_ & 0x01000000) == 0x01000000)) {
        output.writeInt32(26, wCDevTax_);
      }
      if (((bitField0_ & 0x02000000) == 0x02000000)) {
        output.writeInt32(27, eCInterest_);
      }
      if (((bitField0_ & 0x04000000) == 0x04000000)) {
        output.writeInt32(28, eCMeterRent_);
      }
      if (((bitField0_ & 0x08000000) == 0x08000000)) {
        output.writeInt32(29, eCFuseCall_);
      }
      if (((bitField0_ & 0x10000000) == 0x10000000)) {
        output.writeInt32(30, eCRent_);
      }
      if (((bitField0_ & 0x20000000) == 0x20000000)) {
        output.writeInt32(31, lFRebate_);
      }
      if (((bitField0_ & 0x40000000) == 0x40000000)) {
        output.writeInt32(32, lFInterest_);
      }
      if (((bitField0_ & 0x80000000) == 0x80000000)) {
        output.writeInt32(33, currentMeterReading_);
      }
      if (((bitField1_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(34, monthlyLicenseFee_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameGuardianBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSocietyPlotNumberBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getShopNoBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getAddressBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < contactNumber_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(contactNumber_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getContactNumberList().size();
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, plotArea_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getMouzaBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getEmailIDBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, aDLandRent_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, wCCharges_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, aDConservancy_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, lFFee_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, aDElectricityCharges_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, previousMeterReading_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(18, iD_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, lRStreetLight_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, lRDevTax_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, lRExDevTax_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(22, lRRent_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(23, lRInterest_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(24, lRRebate_);
      }
      if (((bitField0_ & 0x00800000) == 0x00800000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(25, wCInterest_);
      }
      if (((bitField0_ & 0x01000000) == 0x01000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(26, wCDevTax_);
      }
      if (((bitField0_ & 0x02000000) == 0x02000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(27, eCInterest_);
      }
      if (((bitField0_ & 0x04000000) == 0x04000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(28, eCMeterRent_);
      }
      if (((bitField0_ & 0x08000000) == 0x08000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(29, eCFuseCall_);
      }
      if (((bitField0_ & 0x10000000) == 0x10000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(30, eCRent_);
      }
      if (((bitField0_ & 0x20000000) == 0x20000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(31, lFRebate_);
      }
      if (((bitField0_ & 0x40000000) == 0x40000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(32, lFInterest_);
      }
      if (((bitField0_ & 0x80000000) == 0x80000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(33, currentMeterReading_);
      }
      if (((bitField1_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(34, monthlyLicenseFee_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.AddressBookProtos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.AddressBookProtos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial.AddressBookProtos.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial.AddressBookProtos.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.AddressBookProtos.internal_static_tutorial_Person_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.AddressBookProtos.internal_static_tutorial_Person_fieldAccessorTable;
      }
      
      // Construct using com.example.tutorial.AddressBookProtos.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        nameGuardian_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        societyPlotNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        shopNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        contactNumber_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        plotArea_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        mouza_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        emailID_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        aDLandRent_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        wCCharges_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        aDConservancy_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        lFFee_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        aDElectricityCharges_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        previousMeterReading_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        iD_ = 0L;
        bitField0_ = (bitField0_ & ~0x00020000);
        lRStreetLight_ = 0;
        bitField0_ = (bitField0_ & ~0x00040000);
        lRDevTax_ = 0;
        bitField0_ = (bitField0_ & ~0x00080000);
        lRExDevTax_ = 0;
        bitField0_ = (bitField0_ & ~0x00100000);
        lRRent_ = 0;
        bitField0_ = (bitField0_ & ~0x00200000);
        lRInterest_ = 0;
        bitField0_ = (bitField0_ & ~0x00400000);
        lRRebate_ = 0;
        bitField0_ = (bitField0_ & ~0x00800000);
        wCInterest_ = 0;
        bitField0_ = (bitField0_ & ~0x01000000);
        wCDevTax_ = 0;
        bitField0_ = (bitField0_ & ~0x02000000);
        eCInterest_ = 0;
        bitField0_ = (bitField0_ & ~0x04000000);
        eCMeterRent_ = 0;
        bitField0_ = (bitField0_ & ~0x08000000);
        eCFuseCall_ = 0;
        bitField0_ = (bitField0_ & ~0x10000000);
        eCRent_ = 0;
        bitField0_ = (bitField0_ & ~0x20000000);
        lFRebate_ = 0;
        bitField0_ = (bitField0_ & ~0x40000000);
        lFInterest_ = 0;
        bitField0_ = (bitField0_ & ~0x80000000);
        currentMeterReading_ = 0;
        bitField1_ = (bitField1_ & ~0x00000001);
        monthlyLicenseFee_ = 0;
        bitField1_ = (bitField1_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.AddressBookProtos.Person.getDescriptor();
      }
      
      public com.example.tutorial.AddressBookProtos.Person getDefaultInstanceForType() {
        return com.example.tutorial.AddressBookProtos.Person.getDefaultInstance();
      }
      
      public com.example.tutorial.AddressBookProtos.Person build() {
        com.example.tutorial.AddressBookProtos.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.example.tutorial.AddressBookProtos.Person buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.example.tutorial.AddressBookProtos.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.example.tutorial.AddressBookProtos.Person buildPartial() {
        com.example.tutorial.AddressBookProtos.Person result = new com.example.tutorial.AddressBookProtos.Person(this);
        int from_bitField0_ = bitField0_;
        int from_bitField1_ = bitField1_;
        int to_bitField0_ = 0;
        int to_bitField1_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userType_ = userType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.nameGuardian_ = nameGuardian_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.societyPlotNumber_ = societyPlotNumber_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.shopNo_ = shopNo_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.address_ = address_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          contactNumber_ = new com.google.protobuf.UnmodifiableLazyStringList(
              contactNumber_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.contactNumber_ = contactNumber_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.plotArea_ = plotArea_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.mouza_ = mouza_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.emailID_ = emailID_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.aDLandRent_ = aDLandRent_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.wCCharges_ = wCCharges_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.aDConservancy_ = aDConservancy_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.lFFee_ = lFFee_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.aDElectricityCharges_ = aDElectricityCharges_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.previousMeterReading_ = previousMeterReading_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.iD_ = iD_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.lRStreetLight_ = lRStreetLight_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.lRDevTax_ = lRDevTax_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.lRExDevTax_ = lRExDevTax_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.lRRent_ = lRRent_;
        if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
          to_bitField0_ |= 0x00200000;
        }
        result.lRInterest_ = lRInterest_;
        if (((from_bitField0_ & 0x00800000) == 0x00800000)) {
          to_bitField0_ |= 0x00400000;
        }
        result.lRRebate_ = lRRebate_;
        if (((from_bitField0_ & 0x01000000) == 0x01000000)) {
          to_bitField0_ |= 0x00800000;
        }
        result.wCInterest_ = wCInterest_;
        if (((from_bitField0_ & 0x02000000) == 0x02000000)) {
          to_bitField0_ |= 0x01000000;
        }
        result.wCDevTax_ = wCDevTax_;
        if (((from_bitField0_ & 0x04000000) == 0x04000000)) {
          to_bitField0_ |= 0x02000000;
        }
        result.eCInterest_ = eCInterest_;
        if (((from_bitField0_ & 0x08000000) == 0x08000000)) {
          to_bitField0_ |= 0x04000000;
        }
        result.eCMeterRent_ = eCMeterRent_;
        if (((from_bitField0_ & 0x10000000) == 0x10000000)) {
          to_bitField0_ |= 0x08000000;
        }
        result.eCFuseCall_ = eCFuseCall_;
        if (((from_bitField0_ & 0x20000000) == 0x20000000)) {
          to_bitField0_ |= 0x10000000;
        }
        result.eCRent_ = eCRent_;
        if (((from_bitField0_ & 0x40000000) == 0x40000000)) {
          to_bitField0_ |= 0x20000000;
        }
        result.lFRebate_ = lFRebate_;
        if (((from_bitField0_ & 0x80000000) == 0x80000000)) {
          to_bitField0_ |= 0x40000000;
        }
        result.lFInterest_ = lFInterest_;
        if (((from_bitField1_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x80000000;
        }
        result.currentMeterReading_ = currentMeterReading_;
        if (((from_bitField1_ & 0x00000002) == 0x00000002)) {
          to_bitField1_ |= 0x00000001;
        }
        result.monthlyLicenseFee_ = monthlyLicenseFee_;
        result.bitField0_ = to_bitField0_;
        result.bitField1_ = to_bitField1_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.AddressBookProtos.Person) {
          return mergeFrom((com.example.tutorial.AddressBookProtos.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.example.tutorial.AddressBookProtos.Person other) {
        if (other == com.example.tutorial.AddressBookProtos.Person.getDefaultInstance()) return this;
        if (other.hasUserType()) {
          setUserType(other.getUserType());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasNameGuardian()) {
          setNameGuardian(other.getNameGuardian());
        }
        if (other.hasSocietyPlotNumber()) {
          setSocietyPlotNumber(other.getSocietyPlotNumber());
        }
        if (other.hasShopNo()) {
          setShopNo(other.getShopNo());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (!other.contactNumber_.isEmpty()) {
          if (contactNumber_.isEmpty()) {
            contactNumber_ = other.contactNumber_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureContactNumberIsMutable();
            contactNumber_.addAll(other.contactNumber_);
          }
          onChanged();
        }
        if (other.hasPlotArea()) {
          setPlotArea(other.getPlotArea());
        }
        if (other.hasMouza()) {
          setMouza(other.getMouza());
        }
        if (other.hasEmailID()) {
          setEmailID(other.getEmailID());
        }
        if (other.hasADLandRent()) {
          setADLandRent(other.getADLandRent());
        }
        if (other.hasWCCharges()) {
          setWCCharges(other.getWCCharges());
        }
        if (other.hasADConservancy()) {
          setADConservancy(other.getADConservancy());
        }
        if (other.hasLFFee()) {
          setLFFee(other.getLFFee());
        }
        if (other.hasADElectricityCharges()) {
          setADElectricityCharges(other.getADElectricityCharges());
        }
        if (other.hasPreviousMeterReading()) {
          setPreviousMeterReading(other.getPreviousMeterReading());
        }
        if (other.hasID()) {
          setID(other.getID());
        }
        if (other.hasLRStreetLight()) {
          setLRStreetLight(other.getLRStreetLight());
        }
        if (other.hasLRDevTax()) {
          setLRDevTax(other.getLRDevTax());
        }
        if (other.hasLRExDevTax()) {
          setLRExDevTax(other.getLRExDevTax());
        }
        if (other.hasLRRent()) {
          setLRRent(other.getLRRent());
        }
        if (other.hasLRInterest()) {
          setLRInterest(other.getLRInterest());
        }
        if (other.hasLRRebate()) {
          setLRRebate(other.getLRRebate());
        }
        if (other.hasWCInterest()) {
          setWCInterest(other.getWCInterest());
        }
        if (other.hasWCDevTax()) {
          setWCDevTax(other.getWCDevTax());
        }
        if (other.hasECInterest()) {
          setECInterest(other.getECInterest());
        }
        if (other.hasECMeterRent()) {
          setECMeterRent(other.getECMeterRent());
        }
        if (other.hasECFuseCall()) {
          setECFuseCall(other.getECFuseCall());
        }
        if (other.hasECRent()) {
          setECRent(other.getECRent());
        }
        if (other.hasLFRebate()) {
          setLFRebate(other.getLFRebate());
        }
        if (other.hasLFInterest()) {
          setLFInterest(other.getLFInterest());
        }
        if (other.hasCurrentMeterReading()) {
          setCurrentMeterReading(other.getCurrentMeterReading());
        }
        if (other.hasMonthlyLicenseFee()) {
          setMonthlyLicenseFee(other.getMonthlyLicenseFee());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserType()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasNameGuardian()) {
          
          return false;
        }
        if (!hasSocietyPlotNumber()) {
          
          return false;
        }
        if (!hasShopNo()) {
          
          return false;
        }
        if (!hasAddress()) {
          
          return false;
        }
        if (!hasPlotArea()) {
          
          return false;
        }
        if (!hasMouza()) {
          
          return false;
        }
        if (!hasEmailID()) {
          
          return false;
        }
        if (!hasADLandRent()) {
          
          return false;
        }
        if (!hasWCCharges()) {
          
          return false;
        }
        if (!hasADConservancy()) {
          
          return false;
        }
        if (!hasLFFee()) {
          
          return false;
        }
        if (!hasADElectricityCharges()) {
          
          return false;
        }
        if (!hasPreviousMeterReading()) {
          
          return false;
        }
        if (!hasID()) {
          
          return false;
        }
        if (!hasLRStreetLight()) {
          
          return false;
        }
        if (!hasLRDevTax()) {
          
          return false;
        }
        if (!hasLRExDevTax()) {
          
          return false;
        }
        if (!hasLRRent()) {
          
          return false;
        }
        if (!hasLRInterest()) {
          
          return false;
        }
        if (!hasLRRebate()) {
          
          return false;
        }
        if (!hasWCInterest()) {
          
          return false;
        }
        if (!hasWCDevTax()) {
          
          return false;
        }
        if (!hasECInterest()) {
          
          return false;
        }
        if (!hasECMeterRent()) {
          
          return false;
        }
        if (!hasECFuseCall()) {
          
          return false;
        }
        if (!hasECRent()) {
          
          return false;
        }
        if (!hasLFRebate()) {
          
          return false;
        }
        if (!hasLFInterest()) {
          
          return false;
        }
        if (!hasCurrentMeterReading()) {
          
          return false;
        }
        if (!hasMonthlyLicenseFee()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userType_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              nameGuardian_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              societyPlotNumber_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              shopNo_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              address_ = input.readBytes();
              break;
            }
            case 66: {
              ensureContactNumberIsMutable();
              contactNumber_.add(input.readBytes());
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              plotArea_ = input.readDouble();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              mouza_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              emailID_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              aDLandRent_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              wCCharges_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              aDConservancy_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              lFFee_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              aDElectricityCharges_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              previousMeterReading_ = input.readInt32();
              break;
            }
            case 144: {
              bitField0_ |= 0x00020000;
              iD_ = input.readInt64();
              break;
            }
            case 152: {
              bitField0_ |= 0x00040000;
              lRStreetLight_ = input.readInt32();
              break;
            }
            case 160: {
              bitField0_ |= 0x00080000;
              lRDevTax_ = input.readInt32();
              break;
            }
            case 168: {
              bitField0_ |= 0x00100000;
              lRExDevTax_ = input.readInt32();
              break;
            }
            case 176: {
              bitField0_ |= 0x00200000;
              lRRent_ = input.readInt32();
              break;
            }
            case 184: {
              bitField0_ |= 0x00400000;
              lRInterest_ = input.readInt32();
              break;
            }
            case 192: {
              bitField0_ |= 0x00800000;
              lRRebate_ = input.readInt32();
              break;
            }
            case 200: {
              bitField0_ |= 0x01000000;
              wCInterest_ = input.readInt32();
              break;
            }
            case 208: {
              bitField0_ |= 0x02000000;
              wCDevTax_ = input.readInt32();
              break;
            }
            case 216: {
              bitField0_ |= 0x04000000;
              eCInterest_ = input.readInt32();
              break;
            }
            case 224: {
              bitField0_ |= 0x08000000;
              eCMeterRent_ = input.readInt32();
              break;
            }
            case 232: {
              bitField0_ |= 0x10000000;
              eCFuseCall_ = input.readInt32();
              break;
            }
            case 240: {
              bitField0_ |= 0x20000000;
              eCRent_ = input.readInt32();
              break;
            }
            case 248: {
              bitField0_ |= 0x40000000;
              lFRebate_ = input.readInt32();
              break;
            }
            case 256: {
              bitField0_ |= 0x80000000;
              lFInterest_ = input.readInt32();
              break;
            }
            case 264: {
              bitField1_ |= 0x00000001;
              currentMeterReading_ = input.readInt32();
              break;
            }
            case 272: {
              bitField1_ |= 0x00000002;
              monthlyLicenseFee_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      private int bitField1_;
      
      // required string user_type = 1;
      private java.lang.Object userType_ = "";
      public boolean hasUserType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserType() {
        java.lang.Object ref = userType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userType_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userType_ = getDefaultInstance().getUserType();
        onChanged();
        return this;
      }
      void setUserType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userType_ = value;
        onChanged();
      }
      
      // required string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // required string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // required string nameGuardian = 4;
      private java.lang.Object nameGuardian_ = "";
      public boolean hasNameGuardian() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getNameGuardian() {
        java.lang.Object ref = nameGuardian_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nameGuardian_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNameGuardian(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nameGuardian_ = value;
        onChanged();
        return this;
      }
      public Builder clearNameGuardian() {
        bitField0_ = (bitField0_ & ~0x00000008);
        nameGuardian_ = getDefaultInstance().getNameGuardian();
        onChanged();
        return this;
      }
      void setNameGuardian(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        nameGuardian_ = value;
        onChanged();
      }
      
      // required string SocietyPlotNumber = 5;
      private java.lang.Object societyPlotNumber_ = "";
      public boolean hasSocietyPlotNumber() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getSocietyPlotNumber() {
        java.lang.Object ref = societyPlotNumber_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          societyPlotNumber_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSocietyPlotNumber(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        societyPlotNumber_ = value;
        onChanged();
        return this;
      }
      public Builder clearSocietyPlotNumber() {
        bitField0_ = (bitField0_ & ~0x00000010);
        societyPlotNumber_ = getDefaultInstance().getSocietyPlotNumber();
        onChanged();
        return this;
      }
      void setSocietyPlotNumber(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        societyPlotNumber_ = value;
        onChanged();
      }
      
      // required string ShopNo = 6;
      private java.lang.Object shopNo_ = "";
      public boolean hasShopNo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getShopNo() {
        java.lang.Object ref = shopNo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          shopNo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setShopNo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        shopNo_ = value;
        onChanged();
        return this;
      }
      public Builder clearShopNo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        shopNo_ = getDefaultInstance().getShopNo();
        onChanged();
        return this;
      }
      void setShopNo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        shopNo_ = value;
        onChanged();
      }
      
      // required string address = 7;
      private java.lang.Object address_ = "";
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000040);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      void setAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        address_ = value;
        onChanged();
      }
      
      // repeated string contactNumber = 8;
      private com.google.protobuf.LazyStringList contactNumber_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureContactNumberIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          contactNumber_ = new com.google.protobuf.LazyStringArrayList(contactNumber_);
          bitField0_ |= 0x00000080;
         }
      }
      public java.util.List<String>
          getContactNumberList() {
        return java.util.Collections.unmodifiableList(contactNumber_);
      }
      public int getContactNumberCount() {
        return contactNumber_.size();
      }
      public String getContactNumber(int index) {
        return contactNumber_.get(index);
      }
      public Builder setContactNumber(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContactNumberIsMutable();
        contactNumber_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addContactNumber(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContactNumberIsMutable();
        contactNumber_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllContactNumber(
          java.lang.Iterable<String> values) {
        ensureContactNumberIsMutable();
        super.addAll(values, contactNumber_);
        onChanged();
        return this;
      }
      public Builder clearContactNumber() {
        contactNumber_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      void addContactNumber(com.google.protobuf.ByteString value) {
        ensureContactNumberIsMutable();
        contactNumber_.add(value);
        onChanged();
      }
      
      // required double plotArea = 9;
      private double plotArea_ ;
      public boolean hasPlotArea() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public double getPlotArea() {
        return plotArea_;
      }
      public Builder setPlotArea(double value) {
        bitField0_ |= 0x00000100;
        plotArea_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlotArea() {
        bitField0_ = (bitField0_ & ~0x00000100);
        plotArea_ = 0D;
        onChanged();
        return this;
      }
      
      // required string Mouza = 10;
      private java.lang.Object mouza_ = "";
      public boolean hasMouza() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getMouza() {
        java.lang.Object ref = mouza_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mouza_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMouza(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        mouza_ = value;
        onChanged();
        return this;
      }
      public Builder clearMouza() {
        bitField0_ = (bitField0_ & ~0x00000200);
        mouza_ = getDefaultInstance().getMouza();
        onChanged();
        return this;
      }
      void setMouza(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        mouza_ = value;
        onChanged();
      }
      
      // required string emailID = 11;
      private java.lang.Object emailID_ = "";
      public boolean hasEmailID() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getEmailID() {
        java.lang.Object ref = emailID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          emailID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmailID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        emailID_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmailID() {
        bitField0_ = (bitField0_ & ~0x00000400);
        emailID_ = getDefaultInstance().getEmailID();
        onChanged();
        return this;
      }
      void setEmailID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        emailID_ = value;
        onChanged();
      }
      
      // required int32 AD_LandRent = 12;
      private int aDLandRent_ ;
      public boolean hasADLandRent() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public int getADLandRent() {
        return aDLandRent_;
      }
      public Builder setADLandRent(int value) {
        bitField0_ |= 0x00000800;
        aDLandRent_ = value;
        onChanged();
        return this;
      }
      public Builder clearADLandRent() {
        bitField0_ = (bitField0_ & ~0x00000800);
        aDLandRent_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 WC_Charges = 13;
      private int wCCharges_ ;
      public boolean hasWCCharges() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getWCCharges() {
        return wCCharges_;
      }
      public Builder setWCCharges(int value) {
        bitField0_ |= 0x00001000;
        wCCharges_ = value;
        onChanged();
        return this;
      }
      public Builder clearWCCharges() {
        bitField0_ = (bitField0_ & ~0x00001000);
        wCCharges_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 AD_Conservancy = 14;
      private int aDConservancy_ ;
      public boolean hasADConservancy() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getADConservancy() {
        return aDConservancy_;
      }
      public Builder setADConservancy(int value) {
        bitField0_ |= 0x00002000;
        aDConservancy_ = value;
        onChanged();
        return this;
      }
      public Builder clearADConservancy() {
        bitField0_ = (bitField0_ & ~0x00002000);
        aDConservancy_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 LF_Fee = 15;
      private int lFFee_ ;
      public boolean hasLFFee() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public int getLFFee() {
        return lFFee_;
      }
      public Builder setLFFee(int value) {
        bitField0_ |= 0x00004000;
        lFFee_ = value;
        onChanged();
        return this;
      }
      public Builder clearLFFee() {
        bitField0_ = (bitField0_ & ~0x00004000);
        lFFee_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 AD_ElectricityCharges = 16;
      private int aDElectricityCharges_ ;
      public boolean hasADElectricityCharges() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public int getADElectricityCharges() {
        return aDElectricityCharges_;
      }
      public Builder setADElectricityCharges(int value) {
        bitField0_ |= 0x00008000;
        aDElectricityCharges_ = value;
        onChanged();
        return this;
      }
      public Builder clearADElectricityCharges() {
        bitField0_ = (bitField0_ & ~0x00008000);
        aDElectricityCharges_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 previousMeterReading = 17;
      private int previousMeterReading_ ;
      public boolean hasPreviousMeterReading() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public int getPreviousMeterReading() {
        return previousMeterReading_;
      }
      public Builder setPreviousMeterReading(int value) {
        bitField0_ |= 0x00010000;
        previousMeterReading_ = value;
        onChanged();
        return this;
      }
      public Builder clearPreviousMeterReading() {
        bitField0_ = (bitField0_ & ~0x00010000);
        previousMeterReading_ = 0;
        onChanged();
        return this;
      }
      
      // required int64 ID = 18;
      private long iD_ ;
      public boolean hasID() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      public long getID() {
        return iD_;
      }
      public Builder setID(long value) {
        bitField0_ |= 0x00020000;
        iD_ = value;
        onChanged();
        return this;
      }
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00020000);
        iD_ = 0L;
        onChanged();
        return this;
      }
      
      // required int32 LR_StreetLight = 19;
      private int lRStreetLight_ ;
      public boolean hasLRStreetLight() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      public int getLRStreetLight() {
        return lRStreetLight_;
      }
      public Builder setLRStreetLight(int value) {
        bitField0_ |= 0x00040000;
        lRStreetLight_ = value;
        onChanged();
        return this;
      }
      public Builder clearLRStreetLight() {
        bitField0_ = (bitField0_ & ~0x00040000);
        lRStreetLight_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 LR_DevTax = 20;
      private int lRDevTax_ ;
      public boolean hasLRDevTax() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      public int getLRDevTax() {
        return lRDevTax_;
      }
      public Builder setLRDevTax(int value) {
        bitField0_ |= 0x00080000;
        lRDevTax_ = value;
        onChanged();
        return this;
      }
      public Builder clearLRDevTax() {
        bitField0_ = (bitField0_ & ~0x00080000);
        lRDevTax_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 LR_ExDevTax = 21;
      private int lRExDevTax_ ;
      public boolean hasLRExDevTax() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      public int getLRExDevTax() {
        return lRExDevTax_;
      }
      public Builder setLRExDevTax(int value) {
        bitField0_ |= 0x00100000;
        lRExDevTax_ = value;
        onChanged();
        return this;
      }
      public Builder clearLRExDevTax() {
        bitField0_ = (bitField0_ & ~0x00100000);
        lRExDevTax_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 LR_Rent = 22;
      private int lRRent_ ;
      public boolean hasLRRent() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      public int getLRRent() {
        return lRRent_;
      }
      public Builder setLRRent(int value) {
        bitField0_ |= 0x00200000;
        lRRent_ = value;
        onChanged();
        return this;
      }
      public Builder clearLRRent() {
        bitField0_ = (bitField0_ & ~0x00200000);
        lRRent_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 LR_Interest = 23;
      private int lRInterest_ ;
      public boolean hasLRInterest() {
        return ((bitField0_ & 0x00400000) == 0x00400000);
      }
      public int getLRInterest() {
        return lRInterest_;
      }
      public Builder setLRInterest(int value) {
        bitField0_ |= 0x00400000;
        lRInterest_ = value;
        onChanged();
        return this;
      }
      public Builder clearLRInterest() {
        bitField0_ = (bitField0_ & ~0x00400000);
        lRInterest_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 LR_Rebate = 24;
      private int lRRebate_ ;
      public boolean hasLRRebate() {
        return ((bitField0_ & 0x00800000) == 0x00800000);
      }
      public int getLRRebate() {
        return lRRebate_;
      }
      public Builder setLRRebate(int value) {
        bitField0_ |= 0x00800000;
        lRRebate_ = value;
        onChanged();
        return this;
      }
      public Builder clearLRRebate() {
        bitField0_ = (bitField0_ & ~0x00800000);
        lRRebate_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 WC_Interest = 25;
      private int wCInterest_ ;
      public boolean hasWCInterest() {
        return ((bitField0_ & 0x01000000) == 0x01000000);
      }
      public int getWCInterest() {
        return wCInterest_;
      }
      public Builder setWCInterest(int value) {
        bitField0_ |= 0x01000000;
        wCInterest_ = value;
        onChanged();
        return this;
      }
      public Builder clearWCInterest() {
        bitField0_ = (bitField0_ & ~0x01000000);
        wCInterest_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 WC_DevTax = 26;
      private int wCDevTax_ ;
      public boolean hasWCDevTax() {
        return ((bitField0_ & 0x02000000) == 0x02000000);
      }
      public int getWCDevTax() {
        return wCDevTax_;
      }
      public Builder setWCDevTax(int value) {
        bitField0_ |= 0x02000000;
        wCDevTax_ = value;
        onChanged();
        return this;
      }
      public Builder clearWCDevTax() {
        bitField0_ = (bitField0_ & ~0x02000000);
        wCDevTax_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 EC_Interest = 27;
      private int eCInterest_ ;
      public boolean hasECInterest() {
        return ((bitField0_ & 0x04000000) == 0x04000000);
      }
      public int getECInterest() {
        return eCInterest_;
      }
      public Builder setECInterest(int value) {
        bitField0_ |= 0x04000000;
        eCInterest_ = value;
        onChanged();
        return this;
      }
      public Builder clearECInterest() {
        bitField0_ = (bitField0_ & ~0x04000000);
        eCInterest_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 EC_MeterRent = 28;
      private int eCMeterRent_ ;
      public boolean hasECMeterRent() {
        return ((bitField0_ & 0x08000000) == 0x08000000);
      }
      public int getECMeterRent() {
        return eCMeterRent_;
      }
      public Builder setECMeterRent(int value) {
        bitField0_ |= 0x08000000;
        eCMeterRent_ = value;
        onChanged();
        return this;
      }
      public Builder clearECMeterRent() {
        bitField0_ = (bitField0_ & ~0x08000000);
        eCMeterRent_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 EC_FuseCall = 29;
      private int eCFuseCall_ ;
      public boolean hasECFuseCall() {
        return ((bitField0_ & 0x10000000) == 0x10000000);
      }
      public int getECFuseCall() {
        return eCFuseCall_;
      }
      public Builder setECFuseCall(int value) {
        bitField0_ |= 0x10000000;
        eCFuseCall_ = value;
        onChanged();
        return this;
      }
      public Builder clearECFuseCall() {
        bitField0_ = (bitField0_ & ~0x10000000);
        eCFuseCall_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 EC_Rent = 30;
      private int eCRent_ ;
      public boolean hasECRent() {
        return ((bitField0_ & 0x20000000) == 0x20000000);
      }
      public int getECRent() {
        return eCRent_;
      }
      public Builder setECRent(int value) {
        bitField0_ |= 0x20000000;
        eCRent_ = value;
        onChanged();
        return this;
      }
      public Builder clearECRent() {
        bitField0_ = (bitField0_ & ~0x20000000);
        eCRent_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 LF_Rebate = 31;
      private int lFRebate_ ;
      public boolean hasLFRebate() {
        return ((bitField0_ & 0x40000000) == 0x40000000);
      }
      public int getLFRebate() {
        return lFRebate_;
      }
      public Builder setLFRebate(int value) {
        bitField0_ |= 0x40000000;
        lFRebate_ = value;
        onChanged();
        return this;
      }
      public Builder clearLFRebate() {
        bitField0_ = (bitField0_ & ~0x40000000);
        lFRebate_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 LF_Interest = 32;
      private int lFInterest_ ;
      public boolean hasLFInterest() {
        return ((bitField0_ & 0x80000000) == 0x80000000);
      }
      public int getLFInterest() {
        return lFInterest_;
      }
      public Builder setLFInterest(int value) {
        bitField0_ |= 0x80000000;
        lFInterest_ = value;
        onChanged();
        return this;
      }
      public Builder clearLFInterest() {
        bitField0_ = (bitField0_ & ~0x80000000);
        lFInterest_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 currentMeterReading = 33;
      private int currentMeterReading_ ;
      public boolean hasCurrentMeterReading() {
        return ((bitField1_ & 0x00000001) == 0x00000001);
      }
      public int getCurrentMeterReading() {
        return currentMeterReading_;
      }
      public Builder setCurrentMeterReading(int value) {
        bitField1_ |= 0x00000001;
        currentMeterReading_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrentMeterReading() {
        bitField1_ = (bitField1_ & ~0x00000001);
        currentMeterReading_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 monthlyLicenseFee = 34;
      private int monthlyLicenseFee_ ;
      public boolean hasMonthlyLicenseFee() {
        return ((bitField1_ & 0x00000002) == 0x00000002);
      }
      public int getMonthlyLicenseFee() {
        return monthlyLicenseFee_;
      }
      public Builder setMonthlyLicenseFee(int value) {
        bitField1_ |= 0x00000002;
        monthlyLicenseFee_ = value;
        onChanged();
        return this;
      }
      public Builder clearMonthlyLicenseFee() {
        bitField1_ = (bitField1_ & ~0x00000002);
        monthlyLicenseFee_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.Person)
    }
    
    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.Person)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Person_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tadd.proto\022\010tutorial\"\277\005\n\006Person\022\021\n\tuser" +
      "_type\030\001 \002(\t\022\r\n\005title\030\002 \002(\t\022\014\n\004name\030\003 \002(\t" +
      "\022\024\n\014nameGuardian\030\004 \002(\t\022\031\n\021SocietyPlotNum" +
      "ber\030\005 \002(\t\022\016\n\006ShopNo\030\006 \002(\t\022\017\n\007address\030\007 \002" +
      "(\t\022\025\n\rcontactNumber\030\010 \003(\t\022\020\n\010plotArea\030\t " +
      "\002(\001\022\r\n\005Mouza\030\n \002(\t\022\017\n\007emailID\030\013 \002(\t\022\023\n\013A" +
      "D_LandRent\030\014 \002(\005\022\022\n\nWC_Charges\030\r \002(\005\022\026\n\016" +
      "AD_Conservancy\030\016 \002(\005\022\016\n\006LF_Fee\030\017 \002(\005\022\035\n\025" +
      "AD_ElectricityCharges\030\020 \002(\005\022\034\n\024previousM" +
      "eterReading\030\021 \002(\005\022\n\n\002ID\030\022 \002(\003\022\026\n\016LR_Stre",
      "etLight\030\023 \002(\005\022\021\n\tLR_DevTax\030\024 \002(\005\022\023\n\013LR_E" +
      "xDevTax\030\025 \002(\005\022\017\n\007LR_Rent\030\026 \002(\005\022\023\n\013LR_Int" +
      "erest\030\027 \002(\005\022\021\n\tLR_Rebate\030\030 \002(\005\022\023\n\013WC_Int" +
      "erest\030\031 \002(\005\022\021\n\tWC_DevTax\030\032 \002(\005\022\023\n\013EC_Int" +
      "erest\030\033 \002(\005\022\024\n\014EC_MeterRent\030\034 \002(\005\022\023\n\013EC_" +
      "FuseCall\030\035 \002(\005\022\017\n\007EC_Rent\030\036 \002(\005\022\021\n\tLF_Re" +
      "bate\030\037 \002(\005\022\023\n\013LF_Interest\030  \002(\005\022\033\n\023curre" +
      "ntMeterReading\030! \002(\005\022\031\n\021monthlyLicenseFe" +
      "e\030\" \002(\005B)\n\024com.example.tutorialB\021Address" +
      "BookProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Person_descriptor,
              new java.lang.String[] { "UserType", "Title", "Name", "NameGuardian", "SocietyPlotNumber", "ShopNo", "Address", "ContactNumber", "PlotArea", "Mouza", "EmailID", "ADLandRent", "WCCharges", "ADConservancy", "LFFee", "ADElectricityCharges", "PreviousMeterReading", "ID", "LRStreetLight", "LRDevTax", "LRExDevTax", "LRRent", "LRInterest", "LRRebate", "WCInterest", "WCDevTax", "ECInterest", "ECMeterRent", "ECFuseCall", "ECRent", "LFRebate", "LFInterest", "CurrentMeterReading", "MonthlyLicenseFee", },
              com.example.tutorial.AddressBookProtos.Person.class,
              com.example.tutorial.AddressBookProtos.Person.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
