/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import com.example.tutorial.Test.test;
import com.example.tutorial.AddressBookProtos.Person;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author arnav
 */
public class FrameTwo extends javax.swing.JFrame {

    /**
     * Creates new form FrameTwo
     */
    public FrameTwo() {
         this.getContentPane().setBackground(Color.white);
        initComponents();
    }

    final DefaultListModel model = new DefaultListModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Hijli Co-operative Society");

        jLabel2.setText("Member");

        jLabel3.setText("Type:");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jLabel5.setText("abcd");

        jLabel6.setText("Mouza");

        jLabel7.setText("mouza");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addGap(75, 75, 75))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(67, 67, 67)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LandRent(String name, String charges, double plotArea, String arrearDues){        
        String values[]=charges.split(" ");
        double v[]=new double[values.length+1];
        System.out.println(charges+"cbkjas");        
        for(int i=0;i<values.length;i++){
            v[i]=Double.parseDouble(values[i]);
        }
        LandRent lr=new LandRent();
        lr.setValues(name, plotArea, v, arrearDues);
        lr.setVisible(true);
    }
    
    private void WaterCharges(String name, String charges, String Category, String arrearDues){
        String values[]=charges.split(" ");
        double v[]=new double[values.length];
        System.out.println("here "+ charges);
        for(int i=0;i<values.length;i++){
            v[i]=Double.parseDouble(values[i]);
        }
        WaterCharge wc=new WaterCharge();
        wc.setValues(name, Category, v, arrearDues);
        wc.setVisible(true);
    }
    
    private void ElectricityCharges(String charges,String name,  String Category, String prevReading){
        String values[]=charges.split(" ");
        double v[]=new double[values.length];
        for(int i=0;i<values.length;i++){
            v[i]=Double.parseDouble(values[i]);
        }
        ElectricityCharge ec=new ElectricityCharge();
        ec.setValues(name, Category, v, prevReading);
        ec.setVisible(true);
    }
    
    public void ArrearDues(String name , String category,String mauza){
        ArrearDues ad=new ArrearDues();
        ad.setValues(name, category,mauza );
        ad.setVisible(true);        
    }
    
    public void OtherCharges(String s, String feeType,String category,  String name ){
       finale thr=new finale();
       thr.setModel();
        /*FrameThree thr=new FrameThree();
        thr.setValues(name, category, feeType, s);
        */thr.setVisible(true);
    }
    public void LicenseFee( String charges,String category,  String name , int fee){
        licenseFee thr=new licenseFee();
        double values[]=new double[3];
        values[0]=(double)fee;
        System.out.print(fee);
        String v[]=charges.split(" ");
        values[1]=Double.parseDouble(v[0]);
        values[2]=Double.parseDouble(v[1]);
        thr.setValues(name, category, values, charges);
        thr.setVisible(true);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String feeType = jList1.getSelectedValue().toString();
        LandRent landRent = new LandRent();
        float charges[] = new float[10];
        if(feeType.equals("Arrear Dues")){
            ArrearDues( jLabel5.getText(), jLabel2.getText(), jLabel7.getText());
            this.setVisible(false);
            return ;
        }
        String s="";
        TCPClient clnt = new TCPClient();
        int check=1;
        if(feeType.equals("Land Rental"))
             s = "c" + jLabel2.getText() + " " + feeType + " " + jLabel7.getText()+ " ";
        else if(feeType.equals("Water Charges"))
            s = "c" + jLabel2.getText() + " " + feeType + " ";
        else if(feeType.equals("Electricity Charges"))
            s = "c" + jLabel2.getText() + " " + feeType + " ";
        else if(feeType.equals("License Fee"))
            s="c"+jLabel2.getText() + " " + feeType + " ";
        else
            check=0;
        try {
            if(check==1){
                clnt.initialise(6787);
                s=clnt.getCharges(s);

            }
        } catch (IOException ex) {
            jOptionPane1.showMessageDialog(this, "Error.");
            this.setVisible(false);
            Home home=new Home();
            home.setVisible(true);
        } catch (Exception ex) {
            jOptionPane1.showMessageDialog(this, "Error.");
            this.setVisible(false);
            Home home=new Home();
            home.setVisible(true);           
        }
        System.out.print("732");
        if(feeType.equals("Land Rental"))
            LandRent(jLabel5.getText(), s, clnt.getPlotArea(), clnt.getArrearDueLandRent());
        else if(feeType.equals("Water Charges"))
            WaterCharges(jLabel5.getText(), s, jLabel2.getText(), clnt.getArrearDueWaterCharges());
        else if(feeType.equals("Electricity Charges"))
            ElectricityCharges(s, jLabel5.getText(), jLabel2.getText(), clnt.getPrevReading());     
        else if(feeType.equals("License Fee"))
           LicenseFee(s, jLabel2.getText(), jLabel5.getText(), clnt.getMontlyFee());
        else
           OtherCharges(s, feeType, jLabel2.getText(), jLabel5.getText()); 
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void changeUserType(String s, String n, String m) {
        jLabel2.setText(s);
        jLabel5.setText(n);
        jLabel7.setText(m);
    }
    public void addToMemberModel() {
        model.addElement("Land Rental");  
        model.addElement("Water Charges"); 
/*        model.addElement("Water Supply Development Tax"); 
        model.addElement("Admission Fee"); 
        model.addElement("Share Money"); 
        model.addElement("Mutation Fee"); 
        model.addElement("Survey Cost"); 
        model.addElement("Suspense");
*/      model.addElement("One Time Charges");
        model.addElement("Arrear Dues");
    }

    public void addToNonMemberModel() {
        model.addElement("Water Charges");
/*        model.addElement("Water Supply");
        model.addElement("Develpoment Tax");
*/    	model.addElement("One Time Charges");
        model.addElement("Arrear Dues");
    }

    public void addToShopkeeperModel() {
        model.addElement("License Fee");
        model.addElement("Electricity Charges");
    //    model.addElement("Donation");
    //    model.addElement("Security Deposit");
          model.addElement("One Time Charge");
          model.addElement("Arrear Dues");
    }

    public void setModel() {
        jList1.setModel(model);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //   new FrameTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
